version: '3.8'

services:

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./project_pinned
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - django_static_volume:/app/static
    environment:
      - DJANGO_SETTINGS_MODULE=project_pinned.settings.prod
    ports:
      - "8000:8000"
    depends_on:
      - redis

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - django_static_volume:/data/static
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend


volumes:
  redis_data:
  django_static_volume: