version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: pinned_db
      POSTGRES_USER: pinned
      POSTGRES_PASSWORD: pinned
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./project_pinned
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project_pinned:/app
      - django_static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - django_static_volume:/data/static
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  redis_data:
  django_static_volume: