version: '3.8'

services:
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  backend:
    image: bnbong/project-pinned:backend
    deploy:
      resources:
        limits:
          cpus: '1'
    volumes:
      - django-static-volume:/app/static
    environment:
      - DJANGO_SETTINGS_MODULE=project_pinned.settings.prod
    ports:
      - "8000:8000"

  frontend:
    image: bnbong/project-pinned:frontend
    ports:
      - "3000:3000"
    command: ["npm", "start"]

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
      - NGINX_CONF_FILE=nginx.conf
    volumes:
      - django-static-volume:/data/static
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"


volumes:
  redis-data:
  django-static-volume:
  postgres_data: