name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Prod
        uses: appleboy/ssh-action@master
        id: deploy-prod
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
             docker compose stop
             docker pull ${{ secrets.DOCKER_REPONAME }}/frontend
             docker pull ${{ secrets.DOCKER_REPONAME }}/backend
             bash scripts/build_prod.sh

